#!/usr/bin/env python3

#
# Copyright (C) 2025 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

import agent
import os


# Check and set default for Z_PUSH_USE_LEGACY_FOLDER_IDS
if not os.getenv("Z_PUSH_USE_LEGACY_FOLDER_IDS"):
    agent.set_env("Z_PUSH_USE_LEGACY_FOLDER_IDS", "False")
