#!/bin/bash

#
# Copyright (C) 2025 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

exec 1>&2

systemctl --user enable webtop.service

systemctl --user restart -T \
    webtop.service \
    apache.service \
    webdav.service \
    pecbridge.service \
    webapp.service \
    z-push.service \
    postgres.service
