#!/usr/bin/env python3

#
# Copyright (C) 2023 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

import agent

# for legacy usage, set default to false
agent.set_env('Z_PUSH_USE_LEGACY_FOLDER_IDS', 'false')
