#!/usr/bin/env python3

#
# Copyright (C) 2025 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

import os
import agent
import semver


# Extract prevous version from the image tag of PREV_IMAGE_URL environment variable
prev_image = os.environ.get('PREV_IMAGE_URL')

if prev_image is not None:
    # Extract the image tag from the URL
    prev_tag= prev_image.split(':')[-1]
    try:
        prev_version = semver.VersionInfo.parse(prev_tag)
        # Check if the previous version is less than or equal to 1.5.4
        if prev_version <= semver.VersionInfo.parse('1.5.4'):
            # Create the directory webtop.properties.d in the module state directory
            os.makedirs(f'{os.environ["AGENT_STATE_DIR"]}/webtop.properties.d', exist_ok=True)
            # Write the 31theme into the webtop.properties.d directory to enable the white/dark nethesis theme
            with open(f'{os.environ["AGENT_STATE_DIR"]}/webtop.properties.d/31theme', 'w') as f:
                f.write('webtop.ui.presets=nethesislight:Nethesis (light)|nethesis-light|nethesis@light,nethesisdark:Nethesis (dark)|nethesis-dark|nethesis@dark\n')
                f.write('webtop.ui.public.theme=nethesis-light\n')
                f.write('webtop.ui.public.laf=nethesis@light\n')
    except ValueError:
        pass
