#!/usr/bin/env python3

#
# Copyright (C) 2023 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

import json
import os
import sys
import agent

config={
        "hostname": os.getenv("WEBTOP_HOSTNAME", ""),
        "request_https_certificate": agent.get_route(os.environ['MODULE_ID']).get('lets_encrypt', False),
        "locale": os.getenv("WEBTOP_LOCALE", "en_US"),
        "timezone": os.getenv("WEBTOP_TIMEZONE", "-"),
        "mail_module": os.getenv("MAIL_MODULE", ""),
        "mail_domain": os.getenv("MAIL_DOMAIN", ""),
        "ejabberd_module": os.getenv("EJABBERD_MODULE", ""),
        "ejabberd_domain": os.getenv("EJABBERD_DOMAIN", ""),
        "webapp": {
            "debug": os.getenv("WEBAPP_JS_DEBUG", 'False').lower() in ('true', '1', 't'),
            "min_memory": int(os.getenv("WEBAPP_MIN_MEMORY", "512")),
            "max_memory": int(os.getenv("WEBAPP_MAX_MEMORY", "1024")),
            },
        "webdav": {
            "debug": os.getenv("WEBDAV_DEBUG", 'False').lower() in ('true', '1', 't'),
            "loglevel": os.getenv("WEBDAV_LOG_LEVEL", "ERROR"),
            },
        "zpush": {
            "loglevel": os.getenv("Z_PUSH_LOG_LEVEL", "ERROR"),
            },
        "pecbridge_admin_mail": os.getenv("PECBRIDGE_ADMIN_MAIL", ""),
        "pecbridge_from_address": os.getenv("PECBRIDGE_FROM_ADDRESS", ""),
        "pecbridge_notify_owner": os.getenv("PECBRIDGE_NOTIFY_OWNER", "all"),
        "phonebook_instance": os.getenv("PHONEBOOK_INSTANCE", ""),
        }

json.dump(config, fp=sys.stdout)
