#!/usr/bin/env python3

#
# Copyright (C) 2022 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

import json
import os

timezone = os.getenv("WEBTOP_TIMEZONE", "UTC")
debug = os.getenv("WEBDAV_DEBUG", "False") == "True"
log_level = os.getenv("WEBDAV_LOG_LEVEL", "ERROR")

config={
        "debug": debug,
        "caldav": True,
        "carddav": True,
        "timezone": f"{timezone}",
        "baseUri": "/webtop-dav/server.php",
	"log": {
		"level": f"{log_level}",
		"file": "php://stdout"
	},
	"api": {
        "baseUrl": "http://localhost:8080/webtop",
		"dav": {
            "url": "/api/com.sonicle.webtop.core/v1",
            "baseUrl": None
            },
        "caldav": {
            "url": "/api/com.sonicle.webtop.calendar/v1",
            "baseUrl": None
            },
        "carddav": {
            "url": "/api/com.sonicle.webtop.contacts/v1",
            "baseUrl": None
            }
        }
     }

with open('webdav_config.json', 'w') as f:
    json.dump(config, f)
