#!/usr/bin/env python3

#
# Copyright (C) 2022 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

import json
import os

timezone = os.getenv("WEBTOP_TIMEZONE", "UTC")
log_level = os.getenv("Z_PUSH_LOG_LEVEL", "ERROR")
imap_server = os.getenv("Z_PUSH_IMAP_SERVER", "10.5.4.1")
smtp_server = os.getenv("Z_PUSH_SMTP_SERVER", "10.5.4.1")
smtp_port = os.getenv("Z_PUSH_SMTP_PORT", "25")
use_legacy_folder_ids = os.getenv("Z_PUSH_USE_LEGACY_FOLDER_IDS", "False") == "True"

config={
        "timezone": f"{timezone}",
        "log": {
            "level": f"{log_level}",
            "file": "php://stdout"
            },
        "mail": {
            "imapServer": f"{imap_server}",
            "smtpServer": f"{smtp_server}",
            "smtpPort": f"{smtp_port}",
            },
        "webtop": {
            "apiBaseUrl": "http://localhost:8080/webtop"
            },
        "state": {
            "useLegacyFolderIds": use_legacy_folder_ids,
            "dir": "/var/log/z-push/state"
            }
        }

with open('z-push_config.json', 'w') as f:
    json.dump(config, f)
