name: "Publish images"

on:
  push:
  workflow_dispatch:

permissions:
  packages: write
  actions: read
  contents: write
  security-events: write

jobs:
  publish-images:
    if: github.run_number > 1
    uses: NethServer/ns8-github-actions/.github/workflows/publish-branch.yml@sdl-extra-cache
    with:
      extra-cache-paths: |
        webtop5-build/webtop-webapp-*.war
        webtop5-build/sql-scripts-*.tar.gz
        webtop5-build/webtop-dav-server-*.tgz
        webtop5-build/webtop-eas-server-*.tgz
        webtop5-build/ListTimeZones.class
        webtop5-build/WebtopPassEncode.class
      extra-cache-key: "maven-build-${{ hashFiles('webtop5-build/VERSION') }}"
    secrets:
      netrcb64: ${{ secrets.NETRCB64 }}
  module:
    needs: publish-images
    uses: NethServer/ns8-github-actions/.github/workflows/module-info.yml@v1
  trivy:
    needs: module
    if: ${{ needs.module.outputs.release == 'stable' || needs.module.outputs.release == 'latest' || github.event_name == 'workflow_dispatch' }}
    uses: NethServer/ns8-github-actions/.github/workflows/scan-with-trivy.yml@v1
    with:
      images: ${{ needs.module.outputs.images }}
