name: "Publish images"

on:
  push:

permissions:
  packages: write

jobs:
  publish-images:
    env:
      PB_DOWNLOAD_TOKEN: ${{ secrets.PB_DOWNLOAD_TOKEN }}
    if: github.run_number > 1
    uses: NethServer/ns8-github-actions/.github/workflows/publish-branch.yml@main
    secrets:
        netrcb64: ${{ secrets.NETRCB64 }}
